from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
import logging
from typing import Optional, List

from backend.app.api.dependencies.auth import get_current_user_npp
from backend.app.services.auth.api_key_service import api_key_service

router = APIRouter()
logger = logging.getLogger("CAKRA_API_KEYS")

class GenerateKeyRequest(BaseModel):
    app_name: str

class APIKeyResponse(BaseModel):
    id: str
    key_prefix: str
    app_name: str
    owner_npp: str
    is_active: bool
    total_requests: int
    created_at: str
    last_used_at: Optional[str]

@router.post("/generate")
async def generate_api_key(
    request: GenerateKeyRequest,
    current_user_npp: Optional[str] = Depends(get_current_user_npp)
):
    """
    Generate a new API Key for an external application.
    Only Admins should be calling this.
    """
    if not current_user_npp:
        raise HTTPException(status_code=401, detail="Login required")

    try:
        result = await api_key_service.generate_api_key(request.app_name, current_user_npp)
        return {
            "status": "success",
            "message": "Kunci API berhasil dibuat. SIMPAN KUNCI INI SEKARANG KARENA TIDAK AKAN DITAMPILKAN LAGI.",
            "raw_key": result["raw_key"],
            "app_name": result["app_name"]
        }
    except Exception as e:
        logger.error(f"Generate API Key error: {e}")
        raise HTTPException(status_code=500, detail="Database error")

@router.get("/list", response_model=List[APIKeyResponse])
async def list_api_keys(
    current_user_npp: Optional[str] = Depends(get_current_user_npp)
):
    """List all API keys generated by the current user (or all if admin)"""
    if not current_user_npp:
        raise HTTPException(status_code=401, detail="Login required")

    try:
        rows = await api_key_service.list_api_keys()
        return [
            APIKeyResponse(
                id=str(r['id']),
                key_prefix=r['key_prefix'],
                app_name=r['app_name'],
                owner_npp=r['owner_npp'],
                is_active=r['is_active'],
                total_requests=r['total_requests'],
                created_at=r['created_at'].isoformat() if hasattr(r['created_at'], 'isoformat') else r['created_at'],
                last_used_at=r['last_used_at'].isoformat() if r['last_used_at'] and hasattr(r['last_used_at'], 'isoformat') else r['last_used_at']
            ) for r in rows
        ]
    except Exception as e:
        logger.error(f"List API Keys error: {e}")
        raise HTTPException(status_code=500, detail="Database error")

@router.delete("/revoke/{key_id}")
async def revoke_api_key(
    key_id: str,
    current_user_npp: Optional[str] = Depends(get_current_user_npp)
):
    """Revoke (deactivate) an API key."""
    if not current_user_npp:
        raise HTTPException(status_code=401, detail="Login required")

    try:
        success = await api_key_service.revoke_api_key(key_id)
        if not success:
            raise HTTPException(status_code=404, detail="API Key not found or already revoked")
            
        return {
            "status": "success",
            "message": "API Key berhasil dicabut/deaktivasi."
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Revoke API Key error: {e}")
        raise HTTPException(status_code=500, detail="Database error")
