from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
import secrets
import hashlib
import logging
from typing import Optional, List
from backend.app.core.database import get_db
from backend.app.api.dependencies.auth import get_current_user_npp

router = APIRouter()
logger = logging.getLogger("CAKRA_API_KEYS")

class GenerateKeyRequest(BaseModel):
    app_name: str

class APIKeyResponse(BaseModel):
    id: str
    key_prefix: str
    app_name: str
    owner_npp: str
    is_active: bool
    total_requests: int
    created_at: str
    last_used_at: Optional[str]

@router.post("/generate")
async def generate_api_key(
    request: GenerateKeyRequest,
    current_user_npp: Optional[str] = Depends(get_current_user_npp)
):
    """
    Generate a new API Key for an external application.
    Only Admins should be calling this.
    """
    if not current_user_npp:
        raise HTTPException(status_code=401, detail="Login required")

    # Double check if user is admin (optional, assuming dashboard restricts UI)
    # But for safety, we allow it to be linked to their NPP.
    
    raw_key = "cakra_live_" + secrets.token_urlsafe(32)
    key_hash = hashlib.sha256(raw_key.encode()).hexdigest()
    key_prefix = raw_key[:16] + "..."

    try:
        async with get_db() as conn:
            await conn.execute("""
                INSERT INTO api_keys (key_hash, key_prefix, app_name, owner_npp)
                VALUES ($1, $2, $3, $4)
            """, key_hash, key_prefix, request.app_name, current_user_npp)
            logger.info(f"🔑 [API_KEY] New key generated for {request.app_name} by {current_user_npp}")
    except Exception as e:
        logger.error(f"Failed to generate API Key: {e}")
        raise HTTPException(status_code=500, detail="Database error")

    return {
        "status": "success",
        "message": "Kunci API berhasil dibuat. SIMPAN KUNCI INI SEKARANG KARENA TIDAK AKAN DITAMPILKAN LAGI.",
        "raw_key": raw_key,
        "app_name": request.app_name
    }

@router.get("/list", response_model=List[APIKeyResponse])
async def list_api_keys(
    current_user_npp: Optional[str] = Depends(get_current_user_npp)
):
    """List all API keys generated by the current user (or all if admin)"""
    if not current_user_npp:
        raise HTTPException(status_code=401, detail="Login required")

    try:
        async with get_db() as conn:
            rows = await conn.fetch("""
                SELECT id, key_prefix, app_name, owner_npp, is_active, total_requests, created_at, last_used_at
                FROM api_keys
                ORDER BY created_at DESC
            """)
            return [
                APIKeyResponse(
                    id=str(r['id']),
                    key_prefix=r['key_prefix'],
                    app_name=r['app_name'],
                    owner_npp=r['owner_npp'],
                    is_active=r['is_active'],
                    total_requests=r['total_requests'],
                    created_at=r['created_at'].isoformat(),
                    last_used_at=r['last_used_at'].isoformat() if r['last_used_at'] else None
                ) for r in rows
            ]
    except Exception as e:
        logger.error(f"Failed to list API Keys: {e}")
        raise HTTPException(status_code=500, detail="Database error")

@router.delete("/revoke/{key_id}")
async def revoke_api_key(
    key_id: str,
    current_user_npp: Optional[str] = Depends(get_current_user_npp)
):
    """Revoke (deactivate) an API key."""
    if not current_user_npp:
        raise HTTPException(status_code=401, detail="Login required")

    try:
        async with get_db() as conn:
            res = await conn.execute("UPDATE api_keys SET is_active = FALSE WHERE id = $1", key_id)
            if res == "UPDATE 0":
                raise HTTPException(status_code=404, detail="API Key not found")
            logger.info(f"🚫 [API_KEY] Key {key_id} revoked by {current_user_npp}")
            return {"status": "success", "message": "API Key berhasil dicabut."}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Failed to revoke API Key: {e}")
        raise HTTPException(status_code=500, detail="Database error")
